version: '3.9'
networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
  app:
    container_name: giveaways
    build: .
    restart: always
    depends_on:
      - cache
    env_file:
      - .env
    networks:
      - app-tier