// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	errors: {
		noPerms: {
			/**
			 * Недостаточно прав для использования команды
			 */
			description: string
			/**
			 * Нужные права
			 */
			field: string
			/**
			 * ` ⚪ {perm} ` ` Вкл `
			 * @param {string} perm
			 */
			value: RequiredParams<'perm'>
		}
		/**
		 * Недостаточно прав для отправки сообщений в канал
		 */
		noSendMessagePerm: string
		noInput: {
			/**
			 * Неверно указано время
			 */
			time: string
			/**
			 * Неверно указан канал
			 */
			channel: string
			/**
			 * Неверно указано кол-во победителей
			 */
			winnersCount: string
		}
	}
	giveaway: {
		modal: {
			/**
			 * Запрос на участие
			 */
			title: string
			/**
			 * Приз
			 */
			prize: string
			/**
			 * Длительность розыгрыша (1d|1h|1m|1s)
			 */
			duration: string
			/**
			 * Кол-во победителей (максимум 20)
			 */
			winnersCount: string
			/**
			 * Название или id канала
			 */
			channel: string
		}
		modalReply: {
			/**
			 * Уточним...
			 */
			title: string
			/**
			 * {type}: {description}
			 * @param {string} description
			 * @param {string} type
			 */
			description: RequiredParams<'description' | 'type'>
		}
		conditions: {
			/**
			 * Нажатие реакции
			 */
			reaction: string
			/**
			 * Нажатие реакции + зайти в войс
			 */
			reactionVoice: string
			/**
			 * Нажатие кнопки
			 */
			button: string
			/**
			 * Нажатие кнопки + зайтие войс
			 */
			buttonVoice: string
		}
		response: {
			/**
			 * Для начала
			 */
			title: string
			/**
			 * Чтобы продолжить **создание розыгрыша** выберите ниже **одно** из **условий**.
			 */
			description: string
			/**
			 * Варианты условий
			 */
			options: string
		}
	}
	'default': {
		/**
		 * Приз
		 */
		prize: string
		/**
		 * Время
		 */
		duration: string
		/**
		 * Кол-во победителей
		 */
		winnersCount: string
		/**
		 * Канал
		 */
		channel: string
		/**
		 * вариант
		 */
		option: string
		/**
		 * Уведомления
		 */
		notification: string
		/**
		 * Вкл
		 */
		on: string
		/**
		 * Выкл
		 */
		off: string
	}
	notification: {
		options: {
			/**
			 * Войс оповещение
			 */
			voiceNotifications: string
			/**
			 * Оповещение о выигрыше
			 */
			winNotifications: string
		}
		/**
		 * Управление уведомлениями
		 */
		title: string
		/**
		 * Выберите нужный пункт для **включения** или **отключения** уведомления о розыгрыше
		 */
		description: string
		/**
		 * Нажимать сюда!
		 */
		placeholder: string
		response: {
			description: {
				/**
				 * Вы успешно изменили ваши настройки
				 */
				text: string
				/**
				 * Было
				 */
				was: string
				/**
				 * Стало
				 */
				is: string
			}
		}
	}
	/**
	 * Администратор
	 */
	admin: string
}

export type TranslationFunctions = {
	errors: {
		noPerms: {
			/**
			 * Недостаточно прав для использования команды
			 */
			description: () => LocalizedString
			/**
			 * Нужные права
			 */
			field: () => LocalizedString
			/**
			 * ` ⚪ {perm} ` ` Вкл `
			 */
			value: (arg: { perm: string }) => LocalizedString
		}
		/**
		 * Недостаточно прав для отправки сообщений в канал
		 */
		noSendMessagePerm: () => LocalizedString
		noInput: {
			/**
			 * Неверно указано время
			 */
			time: () => LocalizedString
			/**
			 * Неверно указан канал
			 */
			channel: () => LocalizedString
			/**
			 * Неверно указано кол-во победителей
			 */
			winnersCount: () => LocalizedString
		}
	}
	giveaway: {
		modal: {
			/**
			 * Запрос на участие
			 */
			title: () => LocalizedString
			/**
			 * Приз
			 */
			prize: () => LocalizedString
			/**
			 * Длительность розыгрыша (1d|1h|1m|1s)
			 */
			duration: () => LocalizedString
			/**
			 * Кол-во победителей (максимум 20)
			 */
			winnersCount: () => LocalizedString
			/**
			 * Название или id канала
			 */
			channel: () => LocalizedString
		}
		modalReply: {
			/**
			 * Уточним...
			 */
			title: () => LocalizedString
			/**
			 * {type}: {description}
			 */
			description: (arg: { description: string, type: string }) => LocalizedString
		}
		conditions: {
			/**
			 * Нажатие реакции
			 */
			reaction: () => LocalizedString
			/**
			 * Нажатие реакции + зайти в войс
			 */
			reactionVoice: () => LocalizedString
			/**
			 * Нажатие кнопки
			 */
			button: () => LocalizedString
			/**
			 * Нажатие кнопки + зайтие войс
			 */
			buttonVoice: () => LocalizedString
		}
		response: {
			/**
			 * Для начала
			 */
			title: () => LocalizedString
			/**
			 * Чтобы продолжить **создание розыгрыша** выберите ниже **одно** из **условий**.
			 */
			description: () => LocalizedString
			/**
			 * Варианты условий
			 */
			options: () => LocalizedString
		}
	}
	'default': {
		/**
		 * Приз
		 */
		prize: () => LocalizedString
		/**
		 * Время
		 */
		duration: () => LocalizedString
		/**
		 * Кол-во победителей
		 */
		winnersCount: () => LocalizedString
		/**
		 * Канал
		 */
		channel: () => LocalizedString
		/**
		 * вариант
		 */
		option: () => LocalizedString
		/**
		 * Уведомления
		 */
		notification: () => LocalizedString
		/**
		 * Вкл
		 */
		on: () => LocalizedString
		/**
		 * Выкл
		 */
		off: () => LocalizedString
	}
	notification: {
		options: {
			/**
			 * Войс оповещение
			 */
			voiceNotifications: () => LocalizedString
			/**
			 * Оповещение о выигрыше
			 */
			winNotifications: () => LocalizedString
		}
		/**
		 * Управление уведомлениями
		 */
		title: () => LocalizedString
		/**
		 * Выберите нужный пункт для **включения** или **отключения** уведомления о розыгрыше
		 */
		description: () => LocalizedString
		/**
		 * Нажимать сюда!
		 */
		placeholder: () => LocalizedString
		response: {
			description: {
				/**
				 * Вы успешно изменили ваши настройки
				 */
				text: () => LocalizedString
				/**
				 * Было
				 */
				was: () => LocalizedString
				/**
				 * Стало
				 */
				is: () => LocalizedString
			}
		}
	}
	/**
	 * Администратор
	 */
	admin: () => LocalizedString
}

export type Formatters = {}
