// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	errors: {
		noPerms: {
			/**
			 * I​n​s​u​f​f​i​c​i​e​n​t​ ​p​e​r​m​i​s​s​i​o​n​s​ ​t​o​ ​u​s​e​ ​t​h​e​ ​c​o​m​m​a​n​d
			 */
			description: string
			/**
			 * R​e​q​u​i​r​e​d​ ​r​i​g​h​t​s
			 */
			field: string
			/**
			 * `​ ​⚪​ ​{​p​e​r​m​}​ ​`​ ​`​ ​O​n​ ​`
			 * @param {string} perm
			 */
			value: RequiredParams<'perm'>
		}
		noInput: {
			/**
			 * T​h​e​ ​t​i​m​e​ ​i​s​ ​i​n​c​o​r​r​e​c​t
			 */
			time: string
			/**
			 * T​h​e​ ​c​h​a​n​n​e​l​ ​i​s​ ​s​p​e​c​i​f​i​e​d​ ​i​n​c​o​r​r​e​c​t​l​y
			 */
			channel: string
			/**
			 * T​h​e​ ​n​u​m​b​e​r​ ​o​f​ ​w​i​n​n​e​r​s​ ​i​s​ ​i​n​c​o​r​r​e​c​t
			 */
			winnersCount: string
			/**
			 * T​h​e​ ​m​e​s​s​a​g​e​ ​I​D​ ​i​s​ ​s​p​e​c​i​f​i​e​d​ ​i​n​c​o​r​r​e​c​t​l​y
			 */
			messageID: string
		}
		/**
		 * N​o​t​ ​e​n​o​u​g​h​ ​p​a​r​t​i​c​i​p​a​n​t​s
		 */
		notEnoughMembers: string
		/**
		 * N​o​t​ ​e​n​o​u​g​h​ ​r​i​g​h​t​s​ ​t​o​ ​s​e​n​d​ ​m​e​s​s​a​g​e​s​ ​t​o​ ​t​h​e​ ​c​h​a​n​n​e​l
		 */
		noSendMessagePerm: string
		/**
		 * E​x​c​e​e​d​e​d​ ​t​h​e​ ​m​a​x​i​m​u​m​ ​n​u​m​b​e​r​ ​o​f​ ​g​i​v​e​a​w​a​y​s​ ​o​n​ ​t​h​e​ ​s​e​r​v​e​r
		 */
		maxGiveaways: string
		/**
		 * T​h​e​r​e​ ​a​r​e​ ​n​o​ ​a​c​t​i​v​e​ ​g​i​v​e​a​w​a​y​s​ ​o​n​ ​t​h​e​ ​s​e​r​v​e​r
		 */
		noServerGiveaways: string
		/**
		 * T​h​e​ ​g​i​v​e​a​w​a​y​s​ ​w​a​s​ ​n​o​t​ ​f​o​u​n​d​ ​o​r​ ​h​a​s​ ​a​l​r​e​a​d​y​ ​b​e​e​n​ ​c​o​m​p​l​e​t​e​d
		 */
		noFoundGiveaways: string
	}
	giveaway: {
		modal: {
			/**
			 * R​e​q​u​e​s​t​ ​f​o​r​ ​p​a​r​t​i​c​i​p​a​t​i​o​n
			 */
			title: string
			/**
			 * P​r​i​z​e
			 */
			prize: string
			/**
			 * S​e​r​v​e​r​ ​c​u​r​r​e​n​c​y
			 */
			prizePlaceholder: string
			/**
			 * D​u​r​a​t​i​o​n​ ​o​f​ ​t​h​e​ ​g​i​v​e​a​w​a​y​ ​(​1​w​|​1​d​|​1​h​|​1​m​|​1​s​)
			 */
			duration: string
			/**
			 * M​a​x​i​m​u​m​ ​g​i​v​e​a​w​a​y​ ​d​u​r​a​t​i​o​n​ ​{​n​u​m​b​e​r​}​ ​w​e​e​k​s
			 * @param {number} number
			 */
			maxDuration: RequiredParams<'number'>
			/**
			 * N​u​m​b​e​r​ ​o​f​ ​w​i​n​n​e​r​s
			 */
			winnersCount: string
			/**
			 * M​a​x​i​m​u​m​ ​n​u​m​b​e​r​ ​o​f​ ​w​i​n​n​e​r​s​ ​{​m​a​x​}
			 * @param {number} max
			 */
			winnersCountPlaceholder: RequiredParams<'max'>
			/**
			 * C​h​a​n​n​e​l​ ​n​a​m​e​ ​o​r​ ​i​d​ ​c​h​a​n​n​e​l
			 */
			channel: string
		}
		modalReply: {
			/**
			 * B​e​ ​c​l​e​a​r​.​.​.
			 */
			title: string
			/**
			 * {​t​y​p​e​}​:​ ​{​d​e​s​c​r​i​p​t​i​o​n​}
			 * @param {string} description
			 * @param {string} type
			 */
			description: RequiredParams<'description' | 'type'>
		}
		voiceCondition: {
			/**
			 * W​i​t​h​ ​v​o​i​c​e
			 */
			voice: string
			/**
			 * W​i​t​h​o​u​t​ ​v​o​i​c​e
			 */
			novoice: string
		}
		accessConditions: {
			/**
			 * P​r​e​s​s​i​n​g​ ​a​ ​r​e​a​c​t​i​o​n
			 */
			reaction: string
			/**
			 * P​r​e​s​s​i​n​g​ ​a​ ​b​u​t​t​o​n
			 */
			button: string
		}
		additionalConditions: {
			/**
			 * S​e​n​d​ ​"​n​"​ ​n​u​m​b​e​r​ ​o​f​ ​m​e​s​s​a​g​e​s
			 */
			type: string
			/**
			 * I​n​v​i​t​e​ ​"​n​"​ ​n​u​m​b​e​r​ ​o​f​ ​u​s​e​r​s
			 */
			invite: string
			/**
			 * G​u​e​s​s​ ​t​h​e​ ​h​i​d​d​e​n​ ​n​u​m​b​e​r
			 */
			guess: string
			/**
			 * L​o​c​a​t​e​d​ ​i​n​ ​a​ ​c​e​r​t​a​i​n​ ​c​a​t​e​g​o​r​y
			 */
			category: string
		}
		response: {
			/**
			 * I​n​ ​t​h​e​ ​b​e​g​i​n​n​i​n​g​.​.​.
			 */
			title: string
			/**
			 * P​a​r​t​i​c​i​p​a​t​i​o​n
			 */
			titleTwo: string
			/**
			 * <​@​{​u​s​e​r​I​D​}​>​,​ ​t​o​ ​c​o​n​t​i​n​u​e​ ​*​*​c​r​e​a​t​i​n​g​ ​a​ ​g​i​v​e​a​w​a​y​*​*​
		​c​h​o​o​s​e​ ​o​n​e​ ​o​f​ ​t​h​e​ ​*​*​b​u​t​t​o​n​s​*​*​ ​b​e​l​o​w​ ​t​h​e​ ​o​n​e​ ​y​o​u​ ​n​e​e​d​.
			 * @param {string} userID
			 */
			description: RequiredParams<'userID'>
			/**
			 * <​@​{​u​s​e​r​I​D​}​>​,​ ​t​o​ ​c​o​n​t​i​n​u​e​ ​*​*​c​r​e​a​t​i​n​g​ ​a​ ​g​i​v​e​a​w​a​y​*​*​
		​c​h​o​o​s​e​ ​t​h​e​ ​b​e​l​o​w​ ​*​*​o​n​e​*​*​ ​f​r​o​m​ ​t​h​e​ ​a​v​a​i​l​a​b​l​e​ ​*​*​c​o​n​d​i​t​i​o​n​s​*​*​.
			 * @param {string} userID
			 */
			descriptionTwo: RequiredParams<'userID'>
			/**
			 * 
		​
		​❗​S​o​m​e​ ​c​o​n​d​i​t​i​o​n​s​ ​a​r​e​ ​a​v​a​i​l​a​b​l​e​ ​w​i​t​h​ ​a​ ​s​u​b​s​c​r​i​p​t​i​o​n​ ​<​:​p​a​t​r​e​o​n​:​1​0​3​3​8​6​8​9​0​1​9​8​2​9​3​7​1​5​8​>​ ​&​ ​<​:​b​o​o​s​t​y​:​1​0​3​3​8​6​8​9​0​0​7​2​0​4​5​5​6​8​0​>
			 */
			noDonate: string
			/**
			 * A​r​e​ ​c​o​n​d​i​t​i​o​n​s​ ​n​o​t​ ​a​v​a​i​l​a​b​l​e​?​?
			 */
			donateString: string
			/**
			 * V​a​r​i​a​n​t​s​ ​o​f​ ​c​o​n​d​i​t​i​o​n​s
			 */
			options: string
		}
		additionalQuestion: {
			/**
			 * L​a​s​t​ ​q​u​e​s​t​i​o​n
			 */
			title: string
			/**
			 * S​p​e​c​i​f​y​ ​t​h​e​ ​n​u​m​b​e​r​ ​o​f​ ​m​e​s​s​a​g​e​s​ ​t​o​ ​p​a​r​t​i​c​i​p​a​t​e​ 
			 */
			type: string
			/**
			 * S​p​e​c​i​f​y​ ​t​h​e​ ​n​u​m​b​e​r​ ​o​f​ ​p​e​o​p​l​e​ ​i​n​v​i​t​e​d​ ​t​o​ ​p​a​r​t​i​c​i​p​a​t​e
			 */
			invite: string
			/**
			 * S​p​e​c​i​f​y​ ​t​h​e​ ​c​a​t​e​g​o​r​y​ ​I​D
			 */
			category: string
			/**
			 * G​u​e​s​s​ ​t​h​e​ ​n​u​m​b​e​r​ ​y​o​u​ ​n​e​e​d​ ​t​o​ ​p​a​r​t​i​c​i​p​a​t​e
			 */
			guess: string
			/**
			 * S​p​e​c​i​f​y​ ​a​ ​h​i​n​t
			 */
			guessPrompt: string
		}
		end: {
			/**
			 * T​h​e​ ​g​i​v​e​a​w​a​y​ ​h​a​s​ ​b​e​e​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​c​o​m​p​l​e​t​e​d
			 */
			response: string
		}
		list: {
			/**
			 * *​*​{​i​n​d​e​x​}​.​*​*​ ​<​@​{​u​s​e​r​I​D​}​>
			 * @param {number} index
			 * @param {string} userID
			 */
			text: RequiredParams<'index' | 'userID'>
			/**
			 * *​*​{​i​n​d​e​x​}​.​*​*​ ​<​@​{​u​s​e​r​I​D​}​>​ ​d​o​n​e​ ​*​*​{​c​u​r​r​e​n​t​}​*​*​ ​f​r​o​m​ ​*​*​{​n​e​e​d​}​*​*
			 * @param {number} current
			 * @param {number} index
			 * @param {string} need
			 * @param {string} userID
			 */
			additionalText: RequiredParams<'current' | 'index' | 'need' | 'userID'>
			/**
			 * *​*​{​i​n​d​e​x​}​.​*​*​ ​<​@​{​u​s​e​r​I​D​}​>​ ​<​:​_​_​:​1​0​2​8​4​6​6​5​1​6​5​3​1​8​9​2​2​2​4​>
			 * @param {number} index
			 * @param {string} userID
			 */
			completedText: RequiredParams<'index' | 'userID'>
			/**
			 * M​e​m​b​e​r​s​ ​o​f​ ​t​h​e​ ​g​i​v​e​a​w​a​y
			 */
			title: string
			/**
			 * P​a​g​e​ ​{​p​a​g​e​}​ ​f​r​o​m​ ​{​p​a​g​e​s​}
			 * @param {number} page
			 * @param {number} pages
			 */
			footer: RequiredParams<'page' | 'pages'>
		}
		verify: {
			/**
			 * Y​o​u​r​ ​p​r​o​g​r​e​s​s
			 */
			title: string
			/**
			 * D​o​n​e​ ​*​*​{​c​u​r​r​e​n​t​}​*​*​ ​f​r​o​m​ ​*​*​{​n​e​e​d​}​*​*
			 * @param {number} current
			 * @param {string} need
			 */
			description: RequiredParams<'current' | 'need'>
			/**
			 * Y​o​u​ ​a​r​e​ ​n​o​t​ ​p​a​r​t​i​c​i​p​a​t​i​n​g​ ​i​n​ ​t​h​e​ ​g​i​v​e​a​w​a​y
			 */
			notIn: string
		}
		updateEmbed: {
			/**
			 * P​a​r​t​i​c​i​p​a​t​e
			 */
			participate: string
			/**
			 * M​e​m​b​e​r​s​ ​-​ ​{​c​o​u​n​t​}
			 * @param {number} count
			 */
			participants: RequiredParams<'count'>
			/**
			 * V​e​r​i​f​y
			 */
			verify: string
		}
		onLeave: {
			/**
			 * P​a​r​t​i​c​i​p​a​t​i​o​n​ ​i​n​ ​t​h​e​ ​g​i​v​e​a​w​a​y
			 */
			title: string
			/**
			 * B​y​ ​l​e​a​v​i​n​g​ ​t​h​e​ ​*​*​v​o​i​c​e​ ​c​h​a​n​n​e​l​*​*​,​ ​y​o​u​'​r​e​ ​r​e​f​u​s​i​n​g​ ​t​o​ ​p​a​r​t​i​c​i​p​a​t​e​ ​i​n​ ​t​h​e​ ​g​i​v​e​a​w​a​y​
		​Y​o​u​ ​h​a​v​e​ ​*​*​2​0​ ​s​e​c​o​n​d​s​*​*​ ​t​o​ ​r​e​t​u​r​n​.
			 */
			description: string
		}
		onReturn: {
			/**
			 * P​a​r​t​i​c​i​p​a​t​i​o​n​ ​i​n​ ​t​h​e​ ​g​i​v​e​a​w​a​y
			 */
			title: string
			/**
			 * O​h​,​ ​y​o​u​'​r​e​ ​b​a​c​k​,​ ​s​o​ ​w​e​'​r​e​ ​l​e​a​v​i​n​g​ ​a​n​ ​e​n​t​r​y​ ​f​o​r​ ​p​a​r​t​i​c​i​p​a​t​i​o​n​ ​i​n​ ​t​h​e​ ​g​i​v​e​a​w​a​y
			 */
			description: string
		}
	}
	createGiveaway: {
		/**
		 * P​r​i​z​e​:​ ​{​p​r​i​z​e​}
		 * @param {string} prize
		 */
		title: RequiredParams<'prize'>
		description: {
			/**
			 * >​ ​T​o​ ​p​a​r​t​i​c​i​p​a​t​e​,​ ​y​o​u​ ​n​e​e​d​ ​t​o​ ​c​l​i​c​k​ ​{​r​e​s​t​}
			 * @param {string} rest
			 */
			'default': RequiredParams<'rest'>
			access: {
				/**
				 * o​n​ ​t​h​e​ ​r​e​a​c​t​i​o​n​ ​"​{​e​m​o​j​i​}​"
				 * @param {string} emoji
				 */
				reaction: RequiredParams<'emoji'>
				/**
				 * o​n​ ​t​h​e​ ​b​u​t​t​o​n​ ​"​*​*​P​a​r​t​i​c​i​p​a​t​e​*​*​"
				 */
				button: string
			}
			/**
			 * 
		​>​ ​a​n​d​ ​j​o​i​n​ ​t​h​e​ ​v​o​i​c​e​ ​c​h​a​n​n​e​l
			 */
			voice: string
			additional: {
				/**
				 * 
			​>​ ​a​n​d​ ​s​e​n​d​ ​{​c​o​u​n​t​}​ ​m​e​s​s​a​g​e​s
				 * @param {string} count
				 */
				type: RequiredParams<'count'>
				/**
				 * 
			​>​ ​a​n​d​ ​i​n​v​i​t​e​ ​{​c​o​u​n​t​}​ ​u​s​e​r​s
				 * @param {string} count
				 */
				invite: RequiredParams<'count'>
				/**
				 * 
			​>​ ​a​n​d​ ​g​u​e​s​s​ ​t​h​e​ ​n​u​m​b​e​r
				 */
				guess: string
				/**
				 * 
			​>​ ​a​n​d​ ​b​e​ ​l​o​c​a​t​e​d​ ​i​n​ ​t​h​e​ ​c​a​t​e​g​o​r​y​ ​*​*​<​#​{​c​o​u​n​t​}​>​*​*
				 * @param {string} count
				 */
				category: RequiredParams<'count'>
			}
			/**
			 * 
		​
		​*​*​F​i​n​i​s​h​:​*​*​ ​<​t​:​{​t​i​m​e​}​:​R​>​
		​[​P​l​e​a​s​e​ ​h​e​l​p​ ​m​e​ ​b​y​ ​v​o​t​i​n​g​!​]​(​h​t​t​p​s​:​/​/​t​o​p​.​g​g​/​b​o​t​/​1​0​1​2​0​8​8​8​7​9​3​7​9​1​2​0​1​4​8​/​v​o​t​e​)
			 * @param {number} time
			 */
			time: RequiredParams<'time'>
		}
		reason: {
			additional: {
				/**
				 * Y​o​u​r​ ​t​a​s​k​:​ ​t​o​ ​s​e​n​d​ ​ ​{​c​o​u​n​t​}​ ​m​e​s​s​a​g​e​s​
			​
		
				 * @param {number} count
				 */
				type: RequiredParams<'count'>
				/**
				 * Y​o​u​r​ ​t​a​s​k​:​ ​i​n​v​i​t​e​ ​*​*​{​c​o​u​n​t​}​*​*​ ​u​s​e​r
				 * @param {number} count
				 */
				invite: RequiredParams<'count'>
				/**
				 * Y​o​u​r​ ​t​a​s​k​:​ ​g​u​e​s​s​ ​t​h​e​ ​*​*​h​i​d​d​e​n​*​*​ ​n​u​m​b​e​r
				 */
				guess: string
			}
		}
		/**
		 * E​n​a​b​l​e​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​ ​/​n​o​t​i​f​y
		 */
		footer: string
	}
	onJoinGiveaway: {
		/**
		 * Y​o​u​ ​a​r​e​ ​a​l​r​e​a​d​y​ ​p​a​r​t​i​c​i​p​a​t​i​n​g
		 */
		alreadyParticipate: string
		/**
		 * *​*​C​o​n​d​i​t​i​o​n​s​:​*​*​ ​C​o​n​n​e​c​t​ ​t​o​ ​a​n​y​ ​v​o​i​c​e​ ​c​h​a​n​n​e​l​ ​o​n​ ​t​h​e​ ​s​e​r​v​e​r
		 */
		noVoice: string
		/**
		 * *​*​C​o​n​d​i​t​i​o​n​s​:​*​*​ ​C​o​n​n​e​c​t​ ​t​o​ ​a​n​y​ ​v​o​i​c​e​ ​c​h​a​n​n​e​l​ ​i​n​ ​t​h​e​ ​c​a​t​e​g​o​r​y​ ​<​#​{​c​a​t​e​g​o​r​y​}​>
		 * @param {string} category
		 */
		noCategory: RequiredParams<'category'>
		voiceCondition: {
			/**
			 * N​o​t​e​:​ ​W​h​e​n​ ​y​o​u​ ​e​x​i​t​ ​t​h​e​ ​*​*​v​o​i​c​e​ ​c​h​a​n​n​e​l​*​*​,​ ​y​o​u​'​l​l​ ​b​e​
		​*​*​r​e​m​o​v​e​d​*​*​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​f​r​o​m​ ​p​a​r​t​i​c​i​p​a​t​i​n​g​ ​i​n​ ​t​h​e​ ​*​*​g​i​v​e​a​w​a​y​*​*
			 */
			voice: string
		}
		/**
		 * M​a​y​ ​l​u​c​k​ ​b​e​ ​o​n​ ​y​o​u​r​ ​s​i​d​e
		 */
		joined: string
		/**
		 * G​u​e​s​s​ ​t​h​e​ ​h​i​d​d​e​n​ ​n​u​m​b​e​r
		 */
		guessNumber: string
		cooldown: {
			/**
			 * D​o​ ​n​o​t​ ​r​u​s​h​.​.
			 */
			title: string
			/**
			 * W​a​i​t​ ​<​t​:​$​{​t​i​m​e​}​:​R​>​ ​a​n​d​ ​t​r​y​ ​a​g​a​i​n
			 * @param {number} time
			 */
			description: RequiredParams<'time'>
		}
		join: {
			/**
			 * N​o​w​ ​y​o​u​ ​a​r​e​ ​p​a​r​t​i​c​i​p​a​t​i​n​g​ ​i​n​ ​t​h​e​ ​g​i​v​e​a​w​a​y
			 */
			title: string
			/**
			 * O​h​,​ ​s​o​m​e​t​h​i​n​g​'​s​ ​w​r​o​n​g
			 */
			errorTitle: string
		}
	}
	'default': {
		/**
		 * P​r​i​z​e
		 */
		prize: string
		/**
		 * T​i​m​e
		 */
		time: string
		/**
		 * D​u​r​a​t​i​o​n
		 */
		duration: string
		/**
		 * W​i​n​n​e​r​s​ ​c​o​u​n​t
		 */
		winnersCount: string
		/**
		 * C​h​a​n​n​e​l
		 */
		channel: string
		/**
		 * O​p​t​i​o​n
		 */
		option: string
		/**
		 * N​o​t​i​f​i​c​a​t​i​o​n​s
		 */
		notification: string
		/**
		 * O​n
		 */
		on: string
		/**
		 * O​f​f
		 */
		off: string
		winnersNouns: {
			/**
			 * w​i​n​n​e​r
			 */
			'0': string
			/**
			 * w​i​n​n​e​r
			 */
			'1': string
			/**
			 * w​i​n​n​e​r​s
			 */
			'2': string
		}
		/**
		 * E​r​r​o​r
		 */
		error: string
		/**
		 * A​c​c​e​p​t
		 */
		accept: string
		/**
		 * R​e​j​e​c​t
		 */
		reject: string
		/**
		 * M​i​s​s​i​n​g
		 */
		missing: string
		/**
		 * E​m​p​t​y​.​.​.
		 */
		empty: string
	}
	endGiveaway: {
		/**
		 * T​h​e​ ​g​i​v​e​a​w​a​y​ ​i​s​ ​o​v​e​r​.
		 */
		title: string
		/**
		 * O​r​g​a​n​i​z​e​r​:​ ​<​@​{​c​r​e​a​t​o​r​I​D​}​>​
	​P​r​i​z​e​:​ ​*​*​{​p​r​i​z​e​}​*​*​
	​W​i​n​n​e​r​:​ ​{​w​i​n​n​e​r​s​}
		 * @param {string} creatorID
		 * @param {string} prize
		 * @param {string} winners
		 */
		description: RequiredParams<'creatorID' | 'prize' | 'winners'>
		/**
		 * T​h​e​ ​w​i​n​n​e​r​ ​w​a​s​ ​s​e​l​e​c​t​e​d​ ​w​i​t​h​ ​h​e​l​p​:​ ​h​t​t​p​s​:​/​/​w​w​w​.​r​a​n​d​o​m​.​o​r​g​/
		 */
		footer: string
		winnersMessage: {
			/**
			 * L​u​c​k​ ​i​s​ ​o​n​ ​y​o​u​r​ ​s​i​d​e
			 */
			title: string
			/**
			 * Y​o​u​ ​w​o​n​ ​i​n​ ​t​h​e​ ​g​i​v​e​a​w​a​y​ ​*​*​{​p​r​i​z​e​}​*​*​,​ ​c​o​n​t​a​c​t​ ​t​h​e​ ​o​r​g​a​n​i​z​e​r​ ​t​o​ ​r​e​c​e​i​v​e​ ​y​o​u​r​ ​a​w​a​r​d​.
			 * @param {string} prize
			 */
			description: RequiredParams<'prize'>
		}
	}
	notification: {
		options: {
			/**
			 * V​o​i​c​e​ ​n​o​t​i​f​i​c​a​t​i​o​n
			 */
			voiceNotifications: string
			/**
			 * N​o​t​i​f​i​c​a​t​i​o​n​ ​o​f​ ​a​ ​w​i​n
			 */
			winNotifications: string
		}
		/**
		 * M​a​n​a​g​i​n​g​ ​n​o​t​i​f​i​c​a​t​i​o​n​s
		 */
		title: string
		/**
		 * S​e​l​e​c​t​ ​t​h​e​ ​r​e​q​u​i​r​e​d​ ​i​t​e​m​ ​t​o​ ​*​*​e​n​a​b​l​e​*​*​ ​o​r​ ​*​*​d​i​s​a​b​l​e​*​*​ ​g​i​v​e​a​w​a​y​s​ ​n​o​t​i​f​i​c​a​t​i​o​n​s
		 */
		description: string
		/**
		 * C​l​i​c​k​ ​h​e​r​e​!
		 */
		placeholder: string
		response: {
			description: {
				/**
				 * S​e​t​t​i​n​g​s​ ​h​a​s​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​b​e​e​n​ ​c​h​a​n​g​e​d
				 */
				text: string
				/**
				 * W​a​s
				 */
				was: string
				/**
				 * H​a​s​ ​b​e​c​o​m​e
				 */
				is: string
			}
		}
	}
	help: {
		buttons: {
			/**
			 * I​n​f​o​r​m​a​t​i​o​n
			 */
			information: string
			/**
			 * C​o​m​m​a​n​d​s
			 */
			commands: string
			/**
			 * A​c​t​i​v​e​ ​g​i​v​e​a​w​a​y​s
			 */
			activeGiveaways: string
			/**
			 * F​e​e​d​b​a​c​k
			 */
			feedback: string
		}
		commands: {
			descriptions: {
				others: {
					/**
					 * <​/​{​c​o​m​m​a​n​d​I​D​}​>​ ​-​ ​D​i​s​p​l​a​y​s​ ​g​e​n​e​r​a​l​ ​i​n​f​o​r​m​a​t​i​o​n​.
					 * @param {string} commandID
					 */
					help: RequiredParams<'commandID'>
					/**
					 * <​/​{​c​o​m​m​a​n​d​I​D​}​>​ ​-​ ​C​h​a​n​g​e​ ​t​h​e​ ​b​o​t​ ​l​a​n​g​u​a​g​e​ ​r​u​/​e​n​.
					 * @param {string} commandID
					 */
					locale: RequiredParams<'commandID'>
				}
				giveaway: {
					/**
					 * <​/​{​c​o​m​m​a​n​d​I​D​}​>​ ​-​ ​S​t​a​r​t​ ​t​h​e​ ​g​i​v​e​a​w​a​y​.
					 * @param {string} commandID
					 */
					gs: RequiredParams<'commandID'>
					/**
					 * <​/​{​c​o​m​m​a​n​d​I​D​}​>​ ​-​ ​E​n​a​b​l​e​\​D​i​s​a​b​l​e​ ​g​i​v​e​a​w​a​y​s​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​ ​i​n​ ​
				​<​:​b​a​c​k​g​r​o​u​n​d​:​9​8​0​7​6​5​4​3​4​4​1​4​5​2​2​3​9​8​>​<​:​b​a​c​k​g​r​o​u​n​d​:​9​8​0​7​6​5​4​3​4​4​1​4​5​2​2​3​9​8​>​p​r​i​v​a​t​e​ ​m​e​s​s​a​g​e​s
					 * @param {string} commandID
					 */
					notify: RequiredParams<'commandID'>
					/**
					 * <​/​{​c​o​m​m​a​n​d​I​D​}​>​ ​+​ ​`​ ​m​e​s​s​a​g​e​I​D​ ​`​
				​<​:​b​a​c​k​g​r​o​u​n​d​:​9​8​0​7​6​5​4​3​4​4​1​4​5​2​2​3​9​8​>​ ​┗​ ​F​i​n​i​s​h​e​s​ ​(​s​e​l​e​c​t​s​ ​t​h​e​ ​w​i​n​n​e​r​)​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​o​r​ ​
				​<​:​b​a​c​k​g​r​o​u​n​d​:​9​8​0​7​6​5​4​3​4​4​1​4​5​2​2​3​9​8​>​<​:​b​a​c​k​g​r​o​u​n​d​:​9​8​0​7​6​5​4​3​4​4​1​4​5​2​2​3​9​8​>​t​h​e​ ​l​a​s​t​ ​g​i​v​e​a​w​a​y​ ​i​n​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​c​h​a​n​n​e​l​.
					 * @param {string} commandID
					 */
					end: RequiredParams<'commandID'>
					/**
					 * <​/​{​c​o​m​m​a​n​d​I​D​}​>​ ​+​ ​`​ ​m​e​s​s​a​g​e​I​D​ ​`​
				​<​:​b​a​c​k​g​r​o​u​n​d​:​9​8​0​7​6​5​4​3​4​4​1​4​5​2​2​3​9​8​>​ ​┗​ ​R​e​r​o​l​l​s​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​o​r​ ​l​a​s​t​ ​g​i​v​e​a​w​a​y​ ​i​n​
				​<​:​b​a​c​k​g​r​o​u​n​d​:​9​8​0​7​6​5​4​3​4​4​1​4​5​2​2​3​9​8​>​<​:​b​a​c​k​g​r​o​u​n​d​:​9​8​0​7​6​5​4​3​4​4​1​4​5​2​2​3​9​8​>​t​h​e​ ​c​u​r​r​e​n​t​ ​c​h​a​n​n​e​l​.
					 * @param {string} commandID
					 */
					reroll: RequiredParams<'commandID'>
				}
			}
			embed: {
				/**
				 * ᅠ​ᅠ​«​H​o​l​d​ ​g​i​v​e​a​w​a​y​s​ ​o​n​ ​y​o​u​r​ ​D​i​s​c​o​r​d​ ​s​e​r​v​e​r​ ​q​u​i​c​k​l​y​ ​a​n​d​ ​e​a​s​i​l​y​!​»
				 */
				footer: string
				/**
				 * >​ ​<​@​{​b​o​t​I​D​}​>​ ​—​ ​a​ ​b​o​t​ ​f​o​r​ ​D​i​s​c​o​r​d​ ​s​e​r​v​e​r​s​,​ ​w​h​i​c​h​ ​h​e​l​p​s​ ​t​o​ ​p​r​o​d​u​c​e​ ​a​u​t​o​m​a​t​i​c​ ​g​i​v​e​a​w​a​y​s​.
				 * @param {string} botID
				 */
				description: RequiredParams<'botID'>
			}
		}
		information: {
			embed: {
				fields: {
					/**
					 * N​a​m​e
					 */
					name: string
					/**
					 * S​e​r​v​e​r​s
					 */
					servers: string
					/**
					 * U​s​e​r​s
					 */
					users: string
					/**
					 * P​l​a​t​f​o​r​m
					 */
					platform: string
					/**
					 * M​e​m​o​r​y
					 */
					memory: string
					/**
					 * A​c​t​i​v​e
					 */
					active: string
				}
				/**
				 * I​n​f​o​r​m​a​t​i​o​n​ ​a​b​o​u​t​ ​t​h​e​ ​b​o​t
				 */
				title: string
				/**
				 * >​>​>​ ​T​h​e​ ​d​e​v​e​l​o​p​e​r​ ​o​f​ ​t​h​e​ ​b​o​t​ ​i​s​ ​<​@​{​d​e​v​I​D​}​>​.​ ​
			​ ​*​*​[​*​*​`​{​d​e​v​T​a​g​}​`​*​*​]​*​*
				 * @param {string} devID
				 * @param {string} devTag
				 */
				description: RequiredParams<'devID' | 'devTag'>
				/**
				 * ᅠ​ᅠ​«​H​o​l​d​ ​g​i​v​e​a​w​a​y​s​ ​o​n​ ​y​o​u​r​ ​D​i​s​c​o​r​d​ ​s​e​r​v​e​r​ ​q​u​i​c​k​l​y​ ​a​n​d​ ​e​a​s​i​l​y​!​»
				 */
				footer: string
			}
		}
		giveaways: {
			fields: {
				noGiveaways: {
					/**
					 * T​h​e​r​e​ ​a​r​e​ ​n​o​ ​a​c​t​i​v​e​ ​g​i​v​e​a​w​a​y​s​ ​o​n​ ​t​h​e​ ​s​e​r​v​e​r
					 */
					name: string
					/**
					 * S​t​a​r​t​ ​t​h​e​ ​g​i​v​e​a​w​a​y​ ​w​i​t​h​ ​t​h​e​ ​c​o​m​m​a​n​d​ ​<​/​g​s​:​1​0​1​2​0​8​8​8​7​9​3​7​9​1​2​0​1​4​8​>
					 */
					value: string
				}
				activeGiveaways: {
					/**
					 * P​r​i​z​e​ ​{​p​r​i​z​e​}
					 * @param {string} prize
					 */
					name: RequiredParams<'prize'>
					/**
					 * C​o​n​d​i​t​i​o​n​s​:​ ​*​*​{​a​c​c​e​s​s​C​o​n​d​i​t​i​o​n​}​*​*​
				​N​u​m​b​e​r​ ​o​f​ ​m​e​m​b​e​r​s​:​ ​*​*​{​c​o​u​n​t​}​*​*​
				​O​r​g​a​n​i​z​e​r​:​ ​<​@​{​c​r​e​a​t​o​r​I​D​}​>​
				​E​n​d​i​n​g​:​ ​<​t​:​{​e​n​d​i​n​g​}​:​R​>
					 * @param {string} accessCondition
					 * @param {number} count
					 * @param {string} creatorID
					 * @param {number} ending
					 */
					value: RequiredParams<'accessCondition' | 'count' | 'creatorID' | 'ending'>
				}
			}
			/**
			 * A​c​t​i​v​e​ ​g​i​v​e​a​w​a​y​s
			 */
			title: string
			/**
			 * >​>​>​ ​N​u​m​b​e​r​ ​o​f​ ​g​i​v​e​a​w​a​y​:​ ​*​*​{​c​o​u​n​t​}​*​*
			 * @param {number} count
			 */
			description: RequiredParams<'count'>
			/**
			 * ᅠ​ᅠ​«​H​o​l​d​ ​g​i​v​e​a​w​a​y​s​ ​o​n​ ​y​o​u​r​ ​D​i​s​c​o​r​d​ ​s​e​r​v​e​r​ ​q​u​i​c​k​l​y​ ​a​n​d​ ​e​a​s​i​l​y​!​»
			 */
			footer: string
		}
		giveaway: {
			/**
			 * ᅠ​
		​ᅠ​ᅠ​ᅠ​ᅠ​ᅠ​ᅠ​�​�​ᅠ​M​a​n​a​g​i​n​g​ ​g​i​v​e​a​w​a​y​s​ᅠ​�​�
			 */
			title: string
		}
		others: {
			/**
			 * ⚙​️​ ​O​t​h​e​r
			 */
			title: string
		}
	}
	/**
	 * A​d​m​i​n​i​s​t​r​a​t​o​r
	 */
	admin: string
	locale: {
		/**
		 * C​h​a​n​g​i​n​g​ ​t​h​e​ ​l​a​n​g​u​a​g​e
		 */
		title: string
		/**
		 * *​*​H​i​!​*​*​ ​n​o​w​ ​I​ ​w​i​l​l​ ​b​e​ ​a​v​a​i​l​a​b​l​e​ ​i​n​ ​*​*​E​n​g​l​i​s​h​*​*​!
		 */
		description: string
	}
}

export type TranslationFunctions = {
	errors: {
		noPerms: {
			/**
			 * Insufficient permissions to use the command
			 */
			description: () => LocalizedString
			/**
			 * Required rights
			 */
			field: () => LocalizedString
			/**
			 * ` ⚪ {perm} ` ` On `
			 */
			value: (arg: { perm: string }) => LocalizedString
		}
		noInput: {
			/**
			 * The time is incorrect
			 */
			time: () => LocalizedString
			/**
			 * The channel is specified incorrectly
			 */
			channel: () => LocalizedString
			/**
			 * The number of winners is incorrect
			 */
			winnersCount: () => LocalizedString
			/**
			 * The message ID is specified incorrectly
			 */
			messageID: () => LocalizedString
		}
		/**
		 * Not enough participants
		 */
		notEnoughMembers: () => LocalizedString
		/**
		 * Not enough rights to send messages to the channel
		 */
		noSendMessagePerm: () => LocalizedString
		/**
		 * Exceeded the maximum number of giveaways on the server
		 */
		maxGiveaways: () => LocalizedString
		/**
		 * There are no active giveaways on the server
		 */
		noServerGiveaways: () => LocalizedString
		/**
		 * The giveaways was not found or has already been completed
		 */
		noFoundGiveaways: () => LocalizedString
	}
	giveaway: {
		modal: {
			/**
			 * Request for participation
			 */
			title: () => LocalizedString
			/**
			 * Prize
			 */
			prize: () => LocalizedString
			/**
			 * Server currency
			 */
			prizePlaceholder: () => LocalizedString
			/**
			 * Duration of the giveaway (1w|1d|1h|1m|1s)
			 */
			duration: () => LocalizedString
			/**
			 * Maximum giveaway duration {number} weeks
			 */
			maxDuration: (arg: { number: number }) => LocalizedString
			/**
			 * Number of winners
			 */
			winnersCount: () => LocalizedString
			/**
			 * Maximum number of winners {max}
			 */
			winnersCountPlaceholder: (arg: { max: number }) => LocalizedString
			/**
			 * Channel name or id channel
			 */
			channel: () => LocalizedString
		}
		modalReply: {
			/**
			 * Be clear...
			 */
			title: () => LocalizedString
			/**
			 * {type}: {description}
			 */
			description: (arg: { description: string, type: string }) => LocalizedString
		}
		voiceCondition: {
			/**
			 * With voice
			 */
			voice: () => LocalizedString
			/**
			 * Without voice
			 */
			novoice: () => LocalizedString
		}
		accessConditions: {
			/**
			 * Pressing a reaction
			 */
			reaction: () => LocalizedString
			/**
			 * Pressing a button
			 */
			button: () => LocalizedString
		}
		additionalConditions: {
			/**
			 * Send "n" number of messages
			 */
			type: () => LocalizedString
			/**
			 * Invite "n" number of users
			 */
			invite: () => LocalizedString
			/**
			 * Guess the hidden number
			 */
			guess: () => LocalizedString
			/**
			 * Located in a certain category
			 */
			category: () => LocalizedString
		}
		response: {
			/**
			 * In the beginning...
			 */
			title: () => LocalizedString
			/**
			 * Participation
			 */
			titleTwo: () => LocalizedString
			/**
			 * <@{userID}>, to continue **creating a giveaway**
		choose one of the **buttons** below the one you need.
			 */
			description: (arg: { userID: string }) => LocalizedString
			/**
			 * <@{userID}>, to continue **creating a giveaway**
		choose the below **one** from the available **conditions**.
			 */
			descriptionTwo: (arg: { userID: string }) => LocalizedString
			/**
			 * 
	
		❗Some conditions are available with a subscription <:patreon:1033868901982937158> & <:boosty:1033868900720455680>
			 */
			noDonate: () => LocalizedString
			/**
			 * Are conditions not available??
			 */
			donateString: () => LocalizedString
			/**
			 * Variants of conditions
			 */
			options: () => LocalizedString
		}
		additionalQuestion: {
			/**
			 * Last question
			 */
			title: () => LocalizedString
			/**
			 * Specify the number of messages to participate 
			 */
			type: () => LocalizedString
			/**
			 * Specify the number of people invited to participate
			 */
			invite: () => LocalizedString
			/**
			 * Specify the category ID
			 */
			category: () => LocalizedString
			/**
			 * Guess the number you need to participate
			 */
			guess: () => LocalizedString
			/**
			 * Specify a hint
			 */
			guessPrompt: () => LocalizedString
		}
		end: {
			/**
			 * The giveaway has been successfully completed
			 */
			response: () => LocalizedString
		}
		list: {
			/**
			 * **{index}.** <@{userID}>
			 */
			text: (arg: { index: number, userID: string }) => LocalizedString
			/**
			 * **{index}.** <@{userID}> done **{current}** from **{need}**
			 */
			additionalText: (arg: { current: number, index: number, need: string, userID: string }) => LocalizedString
			/**
			 * **{index}.** <@{userID}> <:__:1028466516531892224>
			 */
			completedText: (arg: { index: number, userID: string }) => LocalizedString
			/**
			 * Members of the giveaway
			 */
			title: () => LocalizedString
			/**
			 * Page {page} from {pages}
			 */
			footer: (arg: { page: number, pages: number }) => LocalizedString
		}
		verify: {
			/**
			 * Your progress
			 */
			title: () => LocalizedString
			/**
			 * Done **{current}** from **{need}**
			 */
			description: (arg: { current: number, need: string }) => LocalizedString
			/**
			 * You are not participating in the giveaway
			 */
			notIn: () => LocalizedString
		}
		updateEmbed: {
			/**
			 * Participate
			 */
			participate: () => LocalizedString
			/**
			 * Members - {count}
			 */
			participants: (arg: { count: number }) => LocalizedString
			/**
			 * Verify
			 */
			verify: () => LocalizedString
		}
		onLeave: {
			/**
			 * Participation in the giveaway
			 */
			title: () => LocalizedString
			/**
			 * By leaving the **voice channel**, you're refusing to participate in the giveaway
		You have **20 seconds** to return.
			 */
			description: () => LocalizedString
		}
		onReturn: {
			/**
			 * Participation in the giveaway
			 */
			title: () => LocalizedString
			/**
			 * Oh, you're back, so we're leaving an entry for participation in the giveaway
			 */
			description: () => LocalizedString
		}
	}
	createGiveaway: {
		/**
		 * Prize: {prize}
		 */
		title: (arg: { prize: string }) => LocalizedString
		description: {
			/**
			 * > To participate, you need to click {rest}
			 */
			'default': (arg: { rest: string }) => LocalizedString
			access: {
				/**
				 * on the reaction "{emoji}"
				 */
				reaction: (arg: { emoji: string }) => LocalizedString
				/**
				 * on the button "**Participate**"
				 */
				button: () => LocalizedString
			}
			/**
			 * 
		> and join the voice channel
			 */
			voice: () => LocalizedString
			additional: {
				/**
				 * 
			> and send {count} messages
				 */
				type: (arg: { count: string }) => LocalizedString
				/**
				 * 
			> and invite {count} users
				 */
				invite: (arg: { count: string }) => LocalizedString
				/**
				 * 
			> and guess the number
				 */
				guess: () => LocalizedString
				/**
				 * 
			> and be located in the category **<#{count}>**
				 */
				category: (arg: { count: string }) => LocalizedString
			}
			/**
			 * 
	
		**Finish:** <t:{time}:R>
		[Please help me by voting!](https://top.gg/bot/1012088879379120148/vote)
			 */
			time: (arg: { time: number }) => LocalizedString
		}
		reason: {
			additional: {
				/**
				 * Your task: to send  {count} messages
		
		
				 */
				type: (arg: { count: number }) => LocalizedString
				/**
				 * Your task: invite **{count}** user
				 */
				invite: (arg: { count: number }) => LocalizedString
				/**
				 * Your task: guess the **hidden** number
				 */
				guess: () => LocalizedString
			}
		}
		/**
		 * Enable notifications /notify
		 */
		footer: () => LocalizedString
	}
	onJoinGiveaway: {
		/**
		 * You are already participating
		 */
		alreadyParticipate: () => LocalizedString
		/**
		 * **Conditions:** Connect to any voice channel on the server
		 */
		noVoice: () => LocalizedString
		/**
		 * **Conditions:** Connect to any voice channel in the category <#{category}>
		 */
		noCategory: (arg: { category: string }) => LocalizedString
		voiceCondition: {
			/**
			 * Note: When you exit the **voice channel**, you'll be
		**removed** automatically from participating in the **giveaway**
			 */
			voice: () => LocalizedString
		}
		/**
		 * May luck be on your side
		 */
		joined: () => LocalizedString
		/**
		 * Guess the hidden number
		 */
		guessNumber: () => LocalizedString
		cooldown: {
			/**
			 * Do not rush..
			 */
			title: () => LocalizedString
			/**
			 * Wait <t:${time}:R> and try again
			 */
			description: (arg: { time: number }) => LocalizedString
		}
		join: {
			/**
			 * Now you are participating in the giveaway
			 */
			title: () => LocalizedString
			/**
			 * Oh, something's wrong
			 */
			errorTitle: () => LocalizedString
		}
	}
	'default': {
		/**
		 * Prize
		 */
		prize: () => LocalizedString
		/**
		 * Time
		 */
		time: () => LocalizedString
		/**
		 * Duration
		 */
		duration: () => LocalizedString
		/**
		 * Winners count
		 */
		winnersCount: () => LocalizedString
		/**
		 * Channel
		 */
		channel: () => LocalizedString
		/**
		 * Option
		 */
		option: () => LocalizedString
		/**
		 * Notifications
		 */
		notification: () => LocalizedString
		/**
		 * On
		 */
		on: () => LocalizedString
		/**
		 * Off
		 */
		off: () => LocalizedString
		winnersNouns: {
			/**
			 * winner
			 */
			'0': () => LocalizedString
			/**
			 * winner
			 */
			'1': () => LocalizedString
			/**
			 * winners
			 */
			'2': () => LocalizedString
		}
		/**
		 * Error
		 */
		error: () => LocalizedString
		/**
		 * Accept
		 */
		accept: () => LocalizedString
		/**
		 * Reject
		 */
		reject: () => LocalizedString
		/**
		 * Missing
		 */
		missing: () => LocalizedString
		/**
		 * Empty...
		 */
		empty: () => LocalizedString
	}
	endGiveaway: {
		/**
		 * The giveaway is over.
		 */
		title: () => LocalizedString
		/**
		 * Organizer: <@{creatorID}>
	Prize: **{prize}**
	Winner: {winners}
		 */
		description: (arg: { creatorID: string, prize: string, winners: string }) => LocalizedString
		/**
		 * The winner was selected with help: https://www.random.org/
		 */
		footer: () => LocalizedString
		winnersMessage: {
			/**
			 * Luck is on your side
			 */
			title: () => LocalizedString
			/**
			 * You won in the giveaway **{prize}**, contact the organizer to receive your award.
			 */
			description: (arg: { prize: string }) => LocalizedString
		}
	}
	notification: {
		options: {
			/**
			 * Voice notification
			 */
			voiceNotifications: () => LocalizedString
			/**
			 * Notification of a win
			 */
			winNotifications: () => LocalizedString
		}
		/**
		 * Managing notifications
		 */
		title: () => LocalizedString
		/**
		 * Select the required item to **enable** or **disable** giveaways notifications
		 */
		description: () => LocalizedString
		/**
		 * Click here!
		 */
		placeholder: () => LocalizedString
		response: {
			description: {
				/**
				 * Settings has successfully been changed
				 */
				text: () => LocalizedString
				/**
				 * Was
				 */
				was: () => LocalizedString
				/**
				 * Has become
				 */
				is: () => LocalizedString
			}
		}
	}
	help: {
		buttons: {
			/**
			 * Information
			 */
			information: () => LocalizedString
			/**
			 * Commands
			 */
			commands: () => LocalizedString
			/**
			 * Active giveaways
			 */
			activeGiveaways: () => LocalizedString
			/**
			 * Feedback
			 */
			feedback: () => LocalizedString
		}
		commands: {
			descriptions: {
				others: {
					/**
					 * </{commandID}> - Displays general information.
					 */
					help: (arg: { commandID: string }) => LocalizedString
					/**
					 * </{commandID}> - Change the bot language ru/en.
					 */
					locale: (arg: { commandID: string }) => LocalizedString
				}
				giveaway: {
					/**
					 * </{commandID}> - Start the giveaway.
					 */
					gs: (arg: { commandID: string }) => LocalizedString
					/**
					 * </{commandID}> - Enable\Disable giveaways notifications in 
				<:background:980765434414522398><:background:980765434414522398>private messages
					 */
					notify: (arg: { commandID: string }) => LocalizedString
					/**
					 * </{commandID}> + ` messageID `
				<:background:980765434414522398> ┗ Finishes (selects the winner) the specified or 
				<:background:980765434414522398><:background:980765434414522398>the last giveaway in the current channel.
					 */
					end: (arg: { commandID: string }) => LocalizedString
					/**
					 * </{commandID}> + ` messageID `
				<:background:980765434414522398> ┗ Rerolls the specified or last giveaway in
				<:background:980765434414522398><:background:980765434414522398>the current channel.
					 */
					reroll: (arg: { commandID: string }) => LocalizedString
				}
			}
			embed: {
				/**
				 * ᅠᅠ«Hold giveaways on your Discord server quickly and easily!»
				 */
				footer: () => LocalizedString
				/**
				 * > <@{botID}> — a bot for Discord servers, which helps to produce automatic giveaways.
				 */
				description: (arg: { botID: string }) => LocalizedString
			}
		}
		information: {
			embed: {
				fields: {
					/**
					 * Name
					 */
					name: () => LocalizedString
					/**
					 * Servers
					 */
					servers: () => LocalizedString
					/**
					 * Users
					 */
					users: () => LocalizedString
					/**
					 * Platform
					 */
					platform: () => LocalizedString
					/**
					 * Memory
					 */
					memory: () => LocalizedString
					/**
					 * Active
					 */
					active: () => LocalizedString
				}
				/**
				 * Information about the bot
				 */
				title: () => LocalizedString
				/**
				 * >>> The developer of the bot is <@{devID}>. 
			 **[**`{devTag}`**]**
				 */
				description: (arg: { devID: string, devTag: string }) => LocalizedString
				/**
				 * ᅠᅠ«Hold giveaways on your Discord server quickly and easily!»
				 */
				footer: () => LocalizedString
			}
		}
		giveaways: {
			fields: {
				noGiveaways: {
					/**
					 * There are no active giveaways on the server
					 */
					name: () => LocalizedString
					/**
					 * Start the giveaway with the command </gs:1012088879379120148>
					 */
					value: () => LocalizedString
				}
				activeGiveaways: {
					/**
					 * Prize {prize}
					 */
					name: (arg: { prize: string }) => LocalizedString
					/**
					 * Conditions: **{accessCondition}**
				Number of members: **{count}**
				Organizer: <@{creatorID}>
				Ending: <t:{ending}:R>
					 */
					value: (arg: { accessCondition: string, count: number, creatorID: string, ending: number }) => LocalizedString
				}
			}
			/**
			 * Active giveaways
			 */
			title: () => LocalizedString
			/**
			 * >>> Number of giveaway: **{count}**
			 */
			description: (arg: { count: number }) => LocalizedString
			/**
			 * ᅠᅠ«Hold giveaways on your Discord server quickly and easily!»
			 */
			footer: () => LocalizedString
		}
		giveaway: {
			/**
			 * ᅠ
		ᅠᅠᅠᅠᅠᅠ🎉ᅠManaging giveawaysᅠ🎉
			 */
			title: () => LocalizedString
		}
		others: {
			/**
			 * ⚙️ Other
			 */
			title: () => LocalizedString
		}
	}
	/**
	 * Administrator
	 */
	admin: () => LocalizedString
	locale: {
		/**
		 * Changing the language
		 */
		title: () => LocalizedString
		/**
		 * **Hi!** now I will be available in **English**!
		 */
		description: () => LocalizedString
	}
}

export type Formatters = {}
